version: '3'

services:
  cakephp4:
    image: shinsenter/cakephp4:latest
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: UTC-3
      PUID: ${UID:-9999}
      PGID: ${GID:-9999}
    depends_on:
      - mariadb
    volumes:
      - ./app:/var/www/html:delegated
    links:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: UTC-3
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quilsoft
    volumes:
      - ./mysql:/var/lib/mysql:delegated